### ISSUE TITLE
misalignment in doc

### ISSUE THREAD

**Issue by foldl** [erlang/otp#5506]
**Describe the bug**
Items should be aligned. See the screen capture below.

It looks like to be caused by `.ghlink-before` style. `-4.5em` fixes it on my settings.

```css
.ghlink-before {
    margin-left: -4em;
    visibility: hidden;
}
```

**To Reproduce**
View the HTML doc.

**Expected behavior**
Things should be aligned.

**Affected versions**
OTP 22~24. Elder versions: not sure

![Screenshot 2021-12-10 142845](https://user-images.githubusercontent.com/4046440/145529265-6ffa2e26-251c-4ebf-a17a-0601a4c3fef2.png)

**Comment by garazdawi** [comment]
Hello! What browser are you using and how large is the browser window? I can see some problems when the browser width is 750 < width < 1000, but not the same problems as on your screenshot.

**Comment by foldl** [comment]
Browser: Edge (96.0.1054.53) on Win11.
Screen Size: 1920x1080.

Oh, it's interesting that the online documentation (https://www.erlang.org/doc/man/crypto.html#Digests%20and%20hash) looks alright. `.ghlink-before` style is:

```css
.ghlink-before {
    visibility: hidden;
}
```
